<?php
/**
 * TodolistApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Todolist RESTful API
 *
 * OpenAPI for Todolist RESTful API
 *
 * OpenAPI spec version: 1
 * Contact: fajarsopian220@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TodolistApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TodolistApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for todolistGet
     *
     * Get all todolist.
     *
     */
    public function testTodolistGet()
    {
    }

    /**
     * Test case for todolistPost
     *
     * Create new todolist.
     *
     */
    public function testTodolistPost()
    {
    }

    /**
     * Test case for todolistTodolistIdDelete
     *
     * Delete existing todolist.
     *
     */
    public function testTodolistTodolistIdDelete()
    {
    }

    /**
     * Test case for todolistTodolistIdPut
     *
     * Update Existing todolist.
     *
     */
    public function testTodolistTodolistIdPut()
    {
    }
}
